# permissions for end users to view mycrdoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mycrdoperator-viewer-role
rules:
- apiGroups:
  - my-crd.beezlabs.com
  resources:
  - mycrdoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - my-crd.beezlabs.com
  resources:
  - mycrdoperators/status
  verbs:
  - get
